APPS-1225-add-file-object-metadata
dnanexus/cwlScala pull request #42
Opened 2022-07-12 22:14 UTC by YuxinShi0423

This PR is to add `metadata` field in the CWL File Object. It is not explicitly supported by CWL v1.2.0 standard, however, cwltool could parse it as a valid map, so users could couple some metadata along with the supplied File object, and propagate them to the Javascript expressions.

Full support of File metadata is expected later this year in CWL v1.2.1. This PR is a quick implementation of metadata that is used only on DNAnexus platform. 

The metadata field is stringified during compilation and then deserialized back to the JSON map in the execution env on the DNAnexus platform. 

The purpose of stringifying the metadata field is that:

- when translating each field its data type is fixed. For example, the File `location` field is expected to be a URI and the `size` is required to be an integer. But the metadata field will have no such limit, in other words, any JSON type might appear.

- Therefore, stringifying the whole metadata field can help safely pack all the metadata values in their original format, so later cwltool can properly process it when executing the source code.

2022-07-13 18:59 UTC, Gvaihir reviewed
Partial review.
Please add tests and update RELEASE_NOTES

2022-07-13 19:53 UTC, Gvaihir requested changes
Minor changes, otherwise good. Pls don't forget unit tests - I know changes might be very surgical but even for the sake of regression down the road

2022-07-13 19:53 UTC, Gvaihir commented on src/main/scala/dx/cwl/CwlValue.scala
> +        None
Why here defaults to `None`? Was there an implementation of smth like `FileImpl.getMetadate()` in the new `cwlJava`?
What's `FileImpl` - just a file uri on the disk?

2022-07-13 19:53 UTC, Gvaihir commented on src/main/scala/dx/cwl/CwlValue.scala
> +            fields.get("metadata").map(_.prettyPrint)
What if `None` returned from `get` here?

2022-07-14 00:34 UTC, YuxinShi0423 commented on src/main/scala/dx/cwl/CwlValue.scala
> +        None
`FileImpl` is part of cwljava to parse the source workflow file and generate `File` object. The current cwl standard does not have metadata as an attr of File, but it is requested by BMS. See my comment in the PR description and https://jira.internal.dnanexus.com/browse/APPS-1225

2022-07-14 00:41 UTC, YuxinShi0423 commented on src/main/scala/dx/cwl/CwlValue.scala
> +            fields.get("metadata").map(_.prettyPrint)
`fields.get("metadata").map(_.prettyPrint)` will return `None` if `metadata` field does not exist.

2022-07-20 16:19 UTC, Gvaihir commented on src/main/scala/dx/cwl/CwlValue.scala
> +            fields.get("metadata").map(_.prettyPrint)
I mean I get _what_ is returned. The question is if `_` is `None` then `None.prettyPrint` should throw an exception at runtime

2022-07-20 16:31 UTC, Gvaihir requested changes

2022-07-20 16:31 UTC, Gvaihir commented on src/test/scala/dx/cwl/CwlValueTest.scala
> +  it should "deserialize the input JSON to File " in {
You introduced metadata into implementation of several `apply` methods of `FileValue`, but testing only one here. For example `apply(file: FileImpl)` where you assign `None` to metadata. But `deserialize` method has `get` on metadata which might be `None`. Try to cover that corner case to make sure you don't get `None.prettyPrint` at some point

2022-07-20 16:31 UTC, Gvaihir commented on src/test/scala/dx/cwl/EvaluatorTest.scala
> +              ) -> FileValue(location = Some(f.toString), metadata = Some(fileMeta.prettyPrint)),
As before - cover one case when metadata is `None`. Here or in `CwlValueTest`

2022-07-20 16:31 UTC, Gvaihir commented
`RELEASE_NOTES` pending

2022-07-20 17:14 UTC, YuxinShi0423 commented on src/main/scala/dx/cwl/CwlValue.scala
> +            fields.get("metadata").map(_.prettyPrint)
> Expression type:
> 
> Option[String]
> Symbol signature:
> 
> final def map[B](f: JsValue => B): Option[B]
> Returns a [scala.Some](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) containing the result of applying f to this [scala.Option](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)'s value if this [scala.Option](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) is nonempty. Otherwise return None.
> 
> This is equivalent to:
> 
> option match {
>   case Some(x) => Some(f(x))
>   case None    => None
> }

2022-07-20 17:15 UTC, YuxinShi0423 commented on src/main/scala/dx/cwl/CwlValue.scala
> +            fields.get("metadata").map(_.prettyPrint)
But you mean it would still do `None.prettyprint`? @Gvaihir

2022-07-22 18:34 UTC, YuxinShi0423 commented
> `RELEASE_NOTES` pending

Shall we make this `metadata` visible to the users at this stage? @commandlinegirl @emiloslavsky

2022-07-22 22:31 UTC, emiloslavsky commented
@YuxinShi0423 the introductory comment needs to be updated; it currently says "The metadata field is stringified during compilation and then deserialized back to the JSON map in the execution env on the DNAnexus platform...."

Please document metadata support as "under development, pending inclusion in CWL standard".

2022-07-29 20:57 UTC, Gvaihir commented on src/main/scala/dx/cwl/CwlValue.scala
> +            fields.get("metadata").map(_.prettyPrint)
I thought so.

2022-07-29 21:49 UTC, Gvaihir approved these changes

2022-07-29 22:03 UTC, merged